name: Cinemax CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validation:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v5
  analyze-code:
    needs: validation
    name: Analyze code
    runs-on: ubuntu-latest
    env:
      CINEMAX_API_KEY: ${{ secrets.CINEMAX_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 21
          cache: gradle
      - name: Run lint
        run: ./gradlew :composeApp:lint
  tests:
    needs: analyze-code
    name: Tests
    runs-on: ubuntu-latest
    env:
      CINEMAX_API_KEY: ${{ secrets.CINEMAX_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 21
          cache: gradle
      - name: Run tests
        run: ./gradlew :composeApp:testDebugUnitTest
  build-android-debug:
    needs: tests
    name: Build Android debug
    runs-on: ubuntu-latest
    env:
      CINEMAX_API_KEY: ${{ secrets.CINEMAX_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 21
          cache: gradle
      - name: Assemble debug
        run: ./gradlew :composeApp:assembleDebug
  build-android-release:
    needs: tests
    name: Build Android release
    runs-on: ubuntu-latest
    env:
      CINEMAX_API_KEY: ${{ secrets.CINEMAX_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 21
          cache: gradle
      - name: Assemble release
        run: ./gradlew :composeApp:assembleRelease
  build-ios-framework:
    needs: tests
    name: Build iOS framework
    runs-on: macos-latest
    env:
      CINEMAX_API_KEY: ${{ secrets.CINEMAX_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 21
          cache: gradle
      - name: Build iOS framework
        run: ./gradlew :composeApp:linkReleaseFrameworkIosArm64
